services:
  format-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_USER: ${GITHUB_USER}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    container_name: format-service
    ports:
      - "${API_PORT}:8083"
    env_file:
      - .env
    networks:
      - snippet-net

volumes:
  gradle-cache:

networks:
  snippet-net:
    external: true